# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1007, 910)
        MainWindow.setStyleSheet("background-image:url(background.jpg)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textbox = QtWidgets.QLabel(self.centralwidget)
        self.textbox.setGeometry(QtCore.QRect(350, 0, 301, 61))
        font = QtGui.QFont()
        font.setFamily("Rosewood Std Regular")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.textbox.setFont(font)
        self.textbox.setObjectName("textbox")
        self.pushButtonUploadfile1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonUploadfile1.setGeometry(QtCore.QRect(350, 80, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonUploadfile1.setFont(font)
        self.pushButtonUploadfile1.setObjectName("pushButtonUploadfile1")
        self.pushButtonUploadfile2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonUploadfile2.setGeometry(QtCore.QRect(790, 80, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonUploadfile2.setFont(font)
        self.pushButtonUploadfile2.setObjectName("pushButtonUploadfile2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(310, 540, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(18)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(50, 130, 431, 371))
        self.listWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listWidget.setDragEnabled(True)
        self.listWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.listWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.listWidget.setObjectName("listWidget")
        self.listWidget_2 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_2.setGeometry(QtCore.QRect(500, 130, 451, 371))
        self.listWidget_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listWidget_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listWidget_2.setDragEnabled(True)
        self.listWidget_2.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.listWidget_2.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.listWidget_2.setObjectName("listWidget_2")
        self.pushButtonClear = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonClear.setGeometry(QtCore.QRect(720, 550, 91, 31))
        self.pushButtonClear.setObjectName("pushButtonClear")
        self.lineEditPath = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditPath.setGeometry(QtCore.QRect(50, 80, 161, 31))
        self.lineEditPath.setObjectName("lineEditPath")
        self.pushButtonUploadUrl = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonUploadUrl.setGeometry(QtCore.QRect(220, 80, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonUploadUrl.setFont(font)
        self.pushButtonUploadUrl.setObjectName("pushButtonUploadUrl")
        self.lineEditPath2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditPath2.setGeometry(QtCore.QRect(500, 80, 161, 31))
        self.lineEditPath2.setObjectName("lineEditPath2")
        self.pushButtonUploadUrl2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonUploadUrl2.setGeometry(QtCore.QRect(670, 80, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonUploadUrl2.setFont(font)
        self.pushButtonUploadUrl2.setObjectName("pushButtonUploadUrl2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(100, 520, 16, 23))
        self.pushButton.setStyleSheet("background-color:#fcdf03")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(100, 580, 16, 23))
        self.pushButton_2.setStyleSheet("background-color:#18aac7")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(100, 640, 16, 23))
        self.pushButton_4.setStyleSheet("background-color:#d41717")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(100, 550, 16, 23))
        self.pushButton_5.setStyleSheet("background-color:#aa00ff")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(100, 610, 16, 23))
        self.pushButton_6.setStyleSheet("background-color:#1f992d")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 520, 71, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 550, 61, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(130, 580, 71, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(130, 610, 61, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(130, 640, 141, 16))
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1007, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textbox.setText(_translate("MainWindow", "ABHED HIGHLIGHTER"))
        self.pushButtonUploadfile1.setText(_translate("MainWindow", "UPLOAD FILE"))
        self.pushButtonUploadfile2.setText(_translate("MainWindow", "UPLOAD FILE"))
        self.pushButton_3.setText(_translate("MainWindow", "CLICK HERE TO COMPARE"))
        self.pushButtonClear.setText(_translate("MainWindow", "CLEAR"))
        self.pushButtonUploadUrl.setText(_translate("MainWindow", "UPLOAD URL"))
        self.pushButtonUploadUrl2.setText(_translate("MainWindow", "UPLOAD URL"))
        self.label.setText(_translate("MainWindow", "100% Similar"))
        self.label_2.setText(_translate("MainWindow", "80% Similar"))
        self.label_3.setText(_translate("MainWindow", "70% Similar"))
        self.label_4.setText(_translate("MainWindow", "60% Similar"))
        self.label_5.setText(_translate("MainWindow", "Not  Similar/Content Error"))
